# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d134be03a7f4c1e5602200af7b9f9e94e9fd3996b6196fee6d01f396e9807ce919ae0b7182c0ca08014062f278370f47d628c9f8c6645ee65782fb99480c6f3b

test:
  secret_key_base: b19554d857ae36f5d0a293b8bded0cf0ccb22914aa9814986586f6ed1b069c2673d6b112da6210bb31ec77aaac83d7b3eb4971ef88f6d7b06e9f487c1b6506e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
